import 'dart:isolate';

import 'model_configs/model_configs.dart';

/// Wire format for messages exchanged between the main isolate (host of
/// `WorkerPool` / `OnnxAiService`) and the worker isolates (running
/// `aiWorkerEntry`).
///
/// All values listed here must be safely sendable across isolate
/// boundaries: no closures, no native FFI handles, only plain data and
/// [SendPort]s.
///
/// Traffic shape:
///   main → worker:  [WorkerInit] once at spawn, then [InferenceRequest]
///   worker → main:  [WorkerReady] one-shot handshake,
///                   then [InferenceSuccess] | [InferenceError] per job

/// One-time setup payload, sent from the main isolate when a worker
/// starts. Carries the full [ModelConfig] so the worker knows the weights
/// path, preprocessing, and output decoding without any name-based
/// guessing. [replyPort] is the channel the worker uses for all of its
/// outbound traffic.
///
/// [ModelConfig] is plain data (path + const presets + enums) and so is
/// safely sendable across the isolate boundary.
class WorkerInit {
  const WorkerInit({
    required this.model,
    required this.replyPort,
  });
  final ModelConfig model;
  final SendPort replyPort;
}

/// A single inference job. [id] is generated by the pool and used to
/// look up the matching [Completer] when the result returns.
class InferenceRequest {
  const InferenceRequest({
    required this.id,
    required this.photoPath,
    required this.photoCacheKey,
  });
  final int id;
  final String photoPath;
  final String photoCacheKey;
}

/// All worker → main messages share this base so the receiver's switch
/// can use exhaustive sealed-class matching.
sealed class WorkerMessage {
  const WorkerMessage();
}

/// Handshake — the worker reports its [SendPort] (where the pool should
/// queue jobs to it). Sent exactly once, after the worker's [OrtSession]
/// finishes loading.
class WorkerReady extends WorkerMessage {
  const WorkerReady(this.commandPort);
  final SendPort commandPort;
}

/// Successful inference for request [id]. Carries the four reporting
/// metrics from [DecodedScore] verbatim — see `output_decoder.dart`.
class InferenceSuccess extends WorkerMessage {
  const InferenceSuccess({
    required this.id,
    required this.photoCacheKey,
    required this.qualityScore,
    required this.sharpnessScore,
    required this.faceCount,
    required this.hasBlink,
  });
  final int id;
  final String photoCacheKey;
  final double qualityScore;
  final double sharpnessScore;
  final int faceCount;
  final bool hasBlink;
}

/// Failed inference. [error] is the exception's `toString` — sending the
/// live object across an isolate boundary is finicky, so we serialize.
class InferenceError extends WorkerMessage {
  const InferenceError({required this.id, required this.error});
  final int id;
  final String error;
}
